### ISSUE TITLE
No resize option?

### ISSUE THREAD

**Issue by kissifrot** [TwicPics/components#2]
Hello,

It seems ratio is used, but we cannot use it with a resize combination. Would it be possible to add the option?

**Comment by jaubourg** [comment]
Hi @kissifrot,

The idea is to size the component using CSS. TwicPics will automatically create the resize API call for you under the hood (even taking the device's DPR into account in the process).

For instance:

```html
<TwicImg
  class="image-class"
  src="path/to/your/image.jpeg"
  ratio="16/9"
></TwicImg>
```

```css
.image-class {
  width: 50%;
}

@media-query ( min-width: 800px ) {
  width: 80%;
}
```

You can also handle ratios using pure CSS for true responsive designs:

```html
<TwicImg
  class="image-class"
  src="path/to/your/image.jpeg"
></TwicImg>
```

```css
.image-class {
  --twic-ratio: calc( 4 / 3 );
  width: 50%;
}


@media-query ( min-width: 800px ) {
  --twic-ratio: calc( 16 / 9 );
  width: 80%;
}
```

You can find more information about all of this in the [documentation](https://github.com/TwicPics/components/blob/main/documentation/README.md).

Would that cover your use-case?

Regards,

Julian
